Done 04-01, 04-02
js-tasks-ru/vue-20220419_aleksandr-guk pull request #7
Opened 2022-06-06 15:33 UTC by AlexandrGuk

2022-06-06 15:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-07 11:11 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-06-09 16:01 UTC, ShGKme requested changes
В целом задачи решены верно. Но предлагаю переписать работу с классами на работу с привязкой объектов классов. Это "стилистические мелочи", но такой подход активно используется во Vue для работы с классами, создан специально для таких задач и привычен для разработчиков. Потому предлагаю с ним лишний раз попрактиковаться.

2022-06-09 16:01 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
Лучше не использовать время (`Date.now`) в качестве идентификатора. Не гарантируется его уникальность. Вместо времени может быть инкрементный идентификатор (просто делать `lastId++` на уровне модуля компонента), или случайный (`nanoid`, `uuid`).

2022-06-09 16:01 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
`some` уже возвращает `Boolean`, можно не приводить его к `Boolean` вновь

2022-06-09 16:01 UTC, ShGKme commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
> +    }
Это вычисляемое свойство не используется и в целом ничего не вычисляет...

2022-06-09 16:01 UTC, ShGKme commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
> +    },
Во Vue, когда требуется добавить класс по условию, удобно использовать синтаксис привязки класса объектом, где ключ - имя класса, а значение - условие добавления.


[https://vuejs.org/guide/essentials/class-and-style.html#class-and-style-bindings](https://vuejs.org/guide/essentials/class-and-style.html#class-and-style-bindings)

Так явно видно, от чего зависит наличие каждого класса, в привычном для Vue разработчиков стиле и удобно добавлять новые классы.

2022-06-09 16:01 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
Аналогично, лучше использовать синтаксис привязки классов с объектом в шаблоне.

2022-06-09 16:01 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  }
Решение с `selectedOption` - корректное. Выбранный вариант лучше вычислять именно вычисляемым свойством.

`dropdownTitle`, `dropdownIcon`, `value` - действительно не самостоятельные свойства.

2022-06-09 16:01 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +        <ui-icon v-if="!!option.icon" :icon="option.icon" class="dropdown__icon"/>
Во Vue в директиве `v-on` обработки события можно писать сразу тело обработчика, без описания функции: `@click="setOption(option)"`

2022-06-09 16:01 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
>      </button>
Привязывать массив классов имеет смысл, когда там несколько элементов. 
`:class="[buttonToggleIconClass]"` - тоже самое, что `:class="buttonToggleIconClass"`

2022-06-10 09:48 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-06-10 10:54 UTC, ShGKme approved these changes
Все задачи приняты 🎉

2022-06-10 10:54 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +}
Не совсем понял, зачем эти стили, но вроде ничего не сломалось...

2022-06-10 10:55 UTC, merged