resolved 06
js-tasks-ru/vue-20220419_aleksandr-guk pull request #9
Opened 2022-06-28 17:08 UTC by AlexandrGuk

2022-06-28 17:09 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-06-28 17:50 UTC, ShGKme requested changes
В `06-wrappers/06-UiInputDate` требуется проксировать все слоты, а не выводить содержимое для конкретного теста :)

Остальные задачи приняты, но есть комментарии.

2022-06-28 17:50 UTC, ShGKme commented on 06-wrappers/04-UiCheckbox/components/UiCheckbox.vue
> +    }
Вся эта часть решения получается работой, дублирующей то, что уже умеет Vue. `customModel` получается значительно более простым решением, не требующим зависеть от встроенных возможностей.

2022-06-28 17:50 UTC, ShGKme commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue
> +  },
`text` - явно вычисляемое свойство, зависящее от `getState`

2022-06-28 17:50 UTC, ShGKme commented on 06-wrappers/05-UiImageUploader/components/UiImageUploader.vue
> +    }
Аналогично `getState` - тоже вычисляемое свойство, вычисляет значение на основе других реактивных данных.

2022-06-28 17:50 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +}
Все эти части - это подстроки у `dateObj.toISOString()`

2022-06-28 17:50 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +        this.$emit('update:modelValue', new Date(Date.UTC(year, Number(month)-1, day, hour, minute)).getTime());
Реализация get здесь не очень сложная, хотя тоже может быть неприятно.
Но и сеттер - не не менее, или даже более неприятный. В тоже время сеттер дублирует то, что браузер уже умеет делать. В `valueAsNumber` у `input` уже есть выбранная дата числом.

2022-06-28 17:50 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
>  </template>
Здесь в `<ui-input>` передаётся фиксированный слот.

```html
<template v-if="$slots['left-icon']" #left-icon><ui-icon class="icon icon-search" icon="search"></ui-icon></template>
```

Это позволяет пройти тест, но это неверное решение. У компонента должны быть такие же слоты, как и у `UIInput`, чтобы при расширении возможности `UiInput` не терять остальные его возможности.

То есть у `UiInputDate` также должен быть слот для иконок, содержимое которого передаётся в `UiInput`. А чтобы руками не прописывать точно такие же слоты, можно проксировать все слоты.

Пример: https://learn.javascript.ru/taskbook/vue-20220419/workspace/wrappers#3-1-proksirovanie-slotov

2022-06-28 18:58 UTC, AlexandrGuk commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +        this.$emit('update:modelValue', new Date(Date.UTC(year, Number(month)-1, day, hour, minute)).getTime());
Я не разобрался как получить valueAsNumber, ведь мне недоступен input :(

2022-06-28 20:31 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +        this.$emit('update:modelValue', new Date(Date.UTC(year, Number(month)-1, day, hour, minute)).getTime());
Первый вариант - через `ref`. Можно установить ref на `UiInput`, а внутри него обратиться в ref на `<input>`.

Второй вариант - вообще не привязываясь к внутренности `UiInput`. Можно подписаться на нативное событие `change`, с которым придёт нативный `event`. В нём есть `target`, где мы обычно доставали `event.target.value`. Также там можно достать и `event.target.valueAsNumber`

2022-06-29 07:45 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-06-29 08:53 UTC, ShGKme approved these changes
Все задачи приняты

2022-06-29 08:54 UTC, merged